 version: '3'
 services:
   database:
     container_name: ecommerce_db
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: ecommerce_db
     ports:
       - "33060:3306"
     volumes:
       - ./ecommerce_script.sql:/docker-entrypoint-initdb.d/ecommerce.sql
       - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf