 version: '3'
 services:
   node:
     build: 
       dockerfile: ./server/Dockerfile
       context: .
     image: node:20
     container_name: ecommerce_api
     tty: true
     stdin_open: true
     command: bash 
     restart: always
     working_dir: /server
     volumes:
       - ./:/server
     ports:
       - 3001:3001
     environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: ecommerce_db
      PORT: '3001'
     depends_on:
       - "database"
   database:
     container_name: ecommerce_db
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: ecommerce_db
     ports:
       - "33060:3306"
     volumes:
       - ./ecommerce_script.sql:/docker-entrypoint-initdb.d/ecommerce.sql
       - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf